import type { NextPage } from 'next'
import Head from 'next/head'
import HomePage from '../components/Home'
import GroomForm from '../components/groomForm'
import BrideForm from '../components/brideForm'
import { useState, useEffect } from 'react'
import Results from '../components/Results'

const Home: NextPage = () => {
  // myForm = Groom Form
  const [myForm, setMyForm] = useState(true)
  const [formComplete, setFormComplete] = useState(true)

  const loadBrideForm = () => {
    setMyForm(!myForm)
 }

  const complete = () => {
    setFormComplete(false)
  }
  return (
    <div>
      <Head>
        <title>Health Match</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {formComplete ? <div className='page w-screen md:flex md:p-2 md:space-x-28'>
            <HomePage/> 
             {myForm ? <GroomForm onClick={loadBrideForm} /> : <BrideForm onClick={complete} /> }
             
        </div> : <Results/>}
        <div className='mb-32'></div>
          </div>
  )
}

export default Home
