import type { NextPage } from 'next'
import Head from 'next/head'
import HomePage from '../components/Home'
import Form from '../components/Form'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Health Match</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='flex'>
            <HomePage/>
        </div>
          </div>
  )
}

export default Home
